version: "3.1"
services:
    www:
        build:
            context: .
            dockerfile: php-apache/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
            - redis
        networks:
            - default

        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_PASSWORD: redisStrongPassowrd@2022
    db:
        image: mysql:8.0
        platform: linux/amd64
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./phpmyadmin/configs:/etc/phpmyadmin/

    redis:
            build:
              context: .
              dockerfile: redis/Dockerfile
            restart: always
            ports:
              - '6379:6379'
            command: redis-server --save 20 1 --loglevel warning --requirepass redisStrongPassowrd@2022
            volumes:
              - ./redis/cache:/data
volumes:
    persistent:
